### ISSUE TITLE
[FEAT] iOS 4차 과제 - Networking

### ISSUE THREAD

**Issue by L-j-h-c** [29th-WE-SOPT-iOS-Part/LeeJunHo#11]
## 📌  Feature Issue
로그인 회원가입에 실제 API 붙이기

## 📝  To-do
- [x] 시작화면 변경 및 프로필 버튼 클릭시 화면전환
- [x] 로그인 기능 구현, 각 상황에 따라 다르게 화면전환
- [x] 회원가입 기능 구현, 각 상황에 따라 다르게 화면전환

## 🍎
- [x] 도전과제 : 로그인 결과값 중 name값을 UserDefaults에 저장하고 확인 화면에서 띄우기

**Comment by Suyeon9911** [comment]
우와 나도 체크할수 있네 ㅋ ㅋ ㅋ
