### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by L-j-h-c** [29th-WE-SOPT-iOS-Part/LeeJunHo#13]
## 📌  Feature Issue
Gesture Recongizer와 데이터 전달

## 📝  To-do
- [x] imageView에 tap Gesture Recognizer 달고 present하기
- [x] 새로운 화면에서 버튼 누를 시 dismiss하기
- [x] tap했을 때 데이터 전달하기
